-- Created by Fred Yang 2015-11-22

-- a).List profits made in November per item
SELECT R.ITEMNO,I.ITEMNAME,
TO_CHAR(SUM(R.QUANTITY*(I.SALEPRICE-I.COSTPRICE)),'$9,999.00') AS PROFIT
FROM TRANSACTION T
JOIN TRANSACTION_ITEM R
ON T.TRANSACTIONID = R.TRANSACTIONID
JOIN ITEM I
ON R.ITEMNO = I.ITEMNO
WHERE T.SUCCEED = 1
AND T.TRANSACTIONDATE >= TO_DATE('20151101','YYYYMMDD')
AND T.TRANSACTIONDATE <= TO_DATE('20151130','YYYYMMDD')
GROUP BY R.ITEMNO, I.ITEMNAME
ORDER BY PROFIT DESC;


-- b).Find which customer made most purchases in November
SELECT T.CUSTOMERID,
(SELECT C.FIRSTNAME || ' ' || C.LASTNAME 
  FROM CUSTOMER C WHERE C.CUSTOMERID = T.CUSTOMERID) AS NAME,
COUNT(DISTINCT T.TRANSACTIONID) AS MOSTPURCHASES
FROM TRANSACTION T
WHERE T.SUCCEED = 1
AND T.CUSTOMERID IS NOT NULL
AND T.TRANSACTIONDATE >= TO_DATE('20151101','YYYYMMDD')
AND T.TRANSACTIONDATE <= TO_DATE('20151130','YYYYMMDD')
GROUP BY T.CUSTOMERID
ORDER BY MOSTPURCHASES DESC;

-- c).List all deliveries that are labeled as Received
SELECT D.DELIVERYID,D.TRANSACTIONID,D.CONSIGNEE,
 (SELECT C.FIRSTNAME || ' ' || C.LASTNAME 
  FROM CUSTOMER C WHERE C.CUSTOMERID = D.CONSIGNEE) AS NAME,
 (SELECT C.ADDRESS FROM CUSTOMER C 
  WHERE C.CUSTOMERID = D.CONSIGNEE) AS ADDRESS,
  D.RECEIVEDATE
 FROM DELIVERY D
 WHERE D.RECEIVEDATE IS NOT NULL;
 